version = "1.0"

[main]
name = "Adguard configuration"

    [main.options]
    name = "Enable some features"

        [main.options.dns_over_https]
        ask = "Enable DNS-over-HTTPS"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "allow_unencrypted_doh:__FINALPATH__/AdGuardHome.yaml"
        services = [ '__APP__' ]